@startuml Get Single Dentist (GET)

header RealHaus Sequence Diagram - Dentists Controller
footer Page %page% of %lastpage%
title "Get Single Dentist (GET /api/v1/dentists/:id)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:dentists" as routerDentists
participant "<<controllers>>\n:dentists" as controllersDentists
participant "<<model>>\n:Dentist" as modelDentist
database "<<MongoDB>>\n:dentists" as DentistsDB

client->server ++:req.get('/api/v1/dentists/:id')
server->routerDentists ++:app.use('/api/v1/dentists',dentists)
routerDentists -> controllersDentists ++:getDentist()

controllersDentists->modelDentist ++:Dentist.findById(req.params.id)
modelDentist->DentistsDB ++: findById()
DentistsDB-->modelDentist --: dentist or null
controllersDentists<--modelDentist --:dentist

alt Dentist not found
    controllersDentists->client --:res.status(404).json({success:false,\nmessage:'Dentist not found with id of ...'})
else Dentist found
    controllersDentists->client --:res.status(200).json({success:true,data:dentist})
end

@enduml
