@startuml Change Password (PUT)

header Dentist Booking System - Users
footer Page %page% of %lastpage%
title "Change Password (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:users" as routerUsers
participant "<<controllers>>\n:users" as controllersUsers
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UsersDatabase

client->server ++:req.put('/api/v1/users/me/password')
server->routerUsers ++:app.use('/api/v1/users',users)
routerUsers -> controllersUsers ++:changePassword()
controllersUsers->controllersUsers:validate input (currentPassword, newPassword)

alt missing input
    controllersUsers->client --:error {success: false, message: 'Please provide current password and new password'}
else input provided
    controllersUsers->modelUser ++:findById(req.user.id).select('+password')
    modelUser ->UsersDatabase ++: find user with password
    UsersDatabase --> modelUser --: user
    controllersUsers <-- modelUser --:user
    
    controllersUsers->controllersUsers:matchPassword(currentPassword)
    
    alt password doesn't match
        controllersUsers->client --:error {success: false, message: 'Current password is incorrect'}
    else password matches
        controllersUsers->controllersUsers:set new password
        controllersUsers->modelUser ++:save()
        modelUser ->UsersDatabase ++: update password
        UsersDatabase --> modelUser --: user
        controllersUsers <-- modelUser --:user
        
        controllersUsers->client --:response {success: true, message: 'Password updated successfully'}
    end
end

@enduml
