@startuml Create Booking (POST)

header Dentist Booking System - Bookings
footer Page %page% of %lastpage%
title "Create Booking (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerBookings
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
participant "<<model>>\n:User" as modelUser
participant "<<model>>\n:Dentist" as modelDentist
database "<<MongoDB>>\n:bookings" as BookingsDatabase
database "<<MongoDB>>\n:users" as UsersDatabase
database "<<MongoDB>>\n:dentists" as DentistsDatabase

client->server ++:req.post('/api/v1/bookings')
server->routerBookings ++:app.use('/api/v1/bookings',bookings)
routerBookings -> controllersBookings ++:createBooking()
controllersBookings->modelBooking ++:findOne({user: req.user.id})
modelBooking ->BookingsDatabase ++: check existing booking
BookingsDatabase --> modelBooking --: existingBooking
controllersBookings <-- modelBooking --:existingBooking

alt user already has booking
    controllersBookings->client --:error {success: false, message: 'You already have a booking'}
else no existing booking
    controllersBookings->modelDentist ++:findById(req.body.dentist)
    modelDentist ->DentistsDatabase ++: find dentist
    DentistsDatabase --> modelDentist --: dentist
    controllersBookings <-- modelDentist --:dentist
    
    alt dentist not found
        controllersBookings->client --:error {success: false, message: 'Dentist not found'}
    else dentist found
        controllersBookings->controllersBookings:check slot availability
        
        alt slot not available
            controllersBookings->client --:error {success: false, message: 'The requested time slot is not available'}
        else slot available
            controllersBookings->modelBooking ++:create(req.body)
            modelBooking ->BookingsDatabase ++: BookingSchema
            BookingsDatabase --> modelBooking --: booking
            controllersBookings <-- modelBooking --:booking
            
            controllersBookings->modelUser ++:findByIdAndUpdate(req.user.id, {booking: booking._id})
            modelUser ->UsersDatabase ++: update user
            UsersDatabase --> modelUser --: updated
            controllersBookings <-- modelUser --:updated
            
            controllersBookings->modelDentist ++:findOneAndUpdate(..., {$set: {'availableSlots.$.isBooked': true}})
            modelDentist ->DentistsDatabase ++: update slot
            DentistsDatabase --> modelDentist --: updated
            controllersBookings <-- modelDentist --:updated
            
            controllersBookings->client --:response {success: true, data: booking}
        end
    end
end

@enduml
