@startuml Login (POST)

header RealHaus Sequence Diagram - Auth Controller
footer Page %page% of %lastpage%
title "Login (POST /api/v1/auth/login)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:users" as UsersDatabase

client->server ++:req.post('/api/v1/auth/login')
server->routerAuth ++:app.use('/api/v1/auth',auth)
routerAuth -> controllersAuth ++:login()

alt Missing email or password
    controllersAuth->client --:res.status(400).json({success:false,\nmsg:'Please provide an email and password'})
else Has email and password
    controllersAuth->modelUser ++:User.findOne({email}).select('+password')
    modelUser ->UsersDatabase ++: find({email})
    UsersDatabase --> modelUser --: user or null

    alt User not found
        controllersAuth <-- modelUser --:null
        controllersAuth->client --:res.status(400).json({success:false,\nmsg:'Invalid credentials'})
    else User found
        controllersAuth <-- modelUser --:user
        controllersAuth->modelUser ++:user.matchPassword(password)
        modelUser-->controllersAuth --:isMatch

        alt Password does not match
            controllersAuth->client --:res.status(401).json({success:false,\nmsg:'Invalid credentials'})
        else Password matches
            controllersAuth->controllersAuth :user.getSignedJwtToken()
            controllersAuth->client --:res.status(200).cookie('token',token).json({success:true,token})
        end
    end
end

@enduml
